version: 1.0.0-build{build}
install:
- ps: dnvm install 1.0.0-rc2-16357 -u
cache:
- C:\Users\appveyor\.dnx\runtimes
- C:\Users\appveyor\.dnx\packages
- C:\projects\watson-core\packages
before_build:
- ps: >-
    dnu restore

    nuget restore

    (Get-Content src\Watson.Core\project.json).replace('"version": "1.0.0-*",', '"version": "' + $env:APPVEYOR_BUILD_VERSION + '",') | Set-Content src\Watson.Core\project.json
build:
  verbosity: minimal
artifacts:
- path: artifacts\**\*.nupkg