version: 1.0.0-build{build}
install:
- ps: dnvm install 1.0.0-rc1-update1
cache:
- C:\Users\appveyor\.dnx\runtimes
- C:\Users\appveyor\.dnx\packages
before_build:
- ps: >-
    dnu restore

    nuget restore

    (Get-Content src\Watson.Core\project.json).replace('"version": "1.0.0-*",', '"version": "' + $env:APPVEYOR_BUILD_VERSION + '",') | Set-Content src\Watson.Core\project.json
build:
  verbosity: minimal
test_script:
- ps: >-
    cd test\Watson.Core.Tests

    dnx test
artifacts:
- path: artifacts\bin\Watson.Core\Debug\*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/damiendennehy/api/v2/package
  api_key:
    secure: VKpWEiDhfRypjFf7MgnSlOJBdzQ1sOT87+aUCzjpj0wAFE8pOLJxcbXPR/6qqVBU
  symbol_server: https://nuget.symbolsource.org/MyGet/damiendennehy